stages:
  - build
  - deploy

build_page:
  image: registry.gitlab.com/gbraad/gitbook-server:3.2.0
  stage: build
  script:
    - gitbook build
    - mv _book public
  artifacts:
    paths:
      - public

publish:
  image: registry.gitlab.com/gbraad/docker:git
  stage: deploy
  script:
    - cd public
    - git init
    - git remote add github https://ylenglish-admin:$GITHUB_TOKEN@github.com/ylenglish/good-english.git
    - git add .
    - git config --global user.email "ylenglish@outlook.com"
    - git config --global user.name "YL English"
    - "git commit -m 'Deployed by GitLab: https://gitlab.com/ylenglish/good-english'"
    - git branch -m gh-pages
    - git push github :gh-pages || echo 1
    - git push github gh-pages


pages:
  stage: deploy
  script:
    - mkdir -p public
  artifacts:
    paths:
      - public
  only:
    - master